apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-hybrid
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://gitlab.io/center-of-enablement/poc/apigee-hybrid-argo.git
    path: applications
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
