apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-preflight
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-99"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apigee
  project: default
  source:
    repoURL: https://gitlab.env.io/center-of-enablement/poc/apigee-hybrid-argo.git
    path: preflight
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
