apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#  annotations:
#    argocd.argoproj.io/sync-wave: "-99"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  source:
    repoURL: https://github.com/mhsvprasad/apigee-hybrid-helm.git
    path: cert-manager
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
