apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-crds
  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#  annotations:
#    argocd.argoproj.io/sync-wave: "-90"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mhsvprasad/apigee-hybrid-helm.git
    path: apigee-crds/apigee-operator/etc/crds/default
    targetRevision: HEAD
#  ignoreDifferences:
#    - group: apiextensions.k8s.io
#      kind: CustomResourceDefinition
#      jqPathExpressions:
#        - .spec.conversion.webhook.clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - ServerSideApply=true

