apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apigee-ingressgateway-manager
  labels:
    apigee.cloud.google.com/platform: apigee
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeroutes
  - apigeedeployments
  - apigeeorganizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update