apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
  name: apigee
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
  name: apigee-system
